version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                working_directory: ~/project/basic-app
                command: yarn install
            - run:
                working_directory: ~/project/basic-app
                command: yarn build
            - run:
                working_directory: ~/project/basic-app
                command: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test